"""post.body_html

Revision ID: 3c5fcec0ae6d
Revises: 600eaf7ebbc0
Create Date: 2016-02-04 11:15:22.516517

"""

# revision identifiers, used by Alembic.
revision = '3c5fcec0ae6d'
down_revision = '600eaf7ebbc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
